import { View, Text } from '@react-pdf/renderer'
import { pdfStyles as styles } from './styles'

interface PDFFooterProps {
  /** Custom footer text (optional) */
  footerText?: string
  /** Show footer */
  showFooter?: boolean
  /** Current page number */
  pageNumber?: number
  /** Total pages */
  totalPages?: number
}

/**
 * PDF Footer Component
 *
 * Displays generation date and optional custom text.
 * Uses fixed positioning at the bottom of the page.
 */
export function PDFFooter({ footerText, showFooter = true, pageNumber, totalPages }: PDFFooterProps) {
  if (!showFooter) {
    return null
  }

  const now = new Date()
  const formattedDate = now.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  return (
    <View style={styles.footer} fixed>
      <Text style={styles.footerText}>{footerText || 'Generated by AstrologerStudio'}</Text>

      <Text style={styles.footerText}>
        {formattedDate}
        {pageNumber && totalPages && ` • Page ${pageNumber} of ${totalPages}`}
      </Text>
    </View>
  )
}
